import { Mail, Lock } from 'lucide-react';
import AmisaCard from '../shared/AmisaCard';
import { businessOfficeMissing } from '../../../data/amisa/_shared/schools';
import { entitlement } from '../../../data/amisa/_shared/suppression';
import { SURVEY_WINDOW } from '../../../data/amisa/_shared/constants';

/**
 * The follow-up list: participating schools that never opened the Business
 * Office section, named, with a contact each.
 *
 * The consequence column is the part that matters. These schools will not see
 * the Business Office benchmark on October 1, and the reason on each row is
 * generated by `entitlement()` — the same function the published summary calls
 * — rather than typed here. A rule described by one function and enforced by
 * another is a rule that eventually disagrees with itself.
 */
export default function MissingSchoolsCard() {
  const missing = businessOfficeMissing();

  return (
    <AmisaCard
      eyebrow="Follow-up · Business Office"
      title={`${missing.length} schools have not started`}
      intro={`The window closes ${SURVEY_WINDOW.closes}. Each row has the coordinator to contact.`}
      source="AMISA Membership Records · contacts are fictional"
      freshness="This morning, 6:00 AM"
      footer={
        <div className="flex items-start gap-2 rounded-lg border border-warning/30 bg-warning/[0.07] px-3 py-2">
          <Lock className="mt-px h-4 w-4 flex-shrink-0 text-warning" aria-hidden="true" />
          <p className="text-[13px] leading-relaxed text-text">
            These {missing.length} schools will not receive the Business Office benchmark. Not as a
            penalty — office data is visible only to schools that entered it. The platform enforces
            it, so nobody has to remember to. They still receive every section they did submit.
          </p>
        </div>
      }
    >
      <div className="overflow-x-auto">
        <table className="w-full min-w-[520px] border-collapse text-left">
          <thead>
            <tr className="border-b border-border-subtle">
              <Th>School</Th>
              <Th>Country</Th>
              <Th>Contact</Th>
              <Th>Status</Th>
            </tr>
          </thead>
          <tbody>
            {missing.map((school) => (
              <tr key={school.id} className="border-b border-border-subtle/60 last:border-0">
                <td className="py-2 pr-3 text-[12.5px] font-medium text-text">{school.name}</td>
                <td className="py-2 pr-3 text-[12px] text-text-muted">{school.country}</td>
                <td className="py-2 pr-3 text-[12px] text-text-muted">
                  <span className="block text-text">{school.contact}</span>
                  <span className="text-[11px]">{school.contactRole}</span>
                </td>
                <td className="py-2 text-[11.5px]">
                  <span className="inline-flex items-center rounded-full border border-warning/35 bg-warning/10 px-2 py-0.5 font-semibold text-warning">
                    Not started
                  </span>
                  <span className="mt-1 block max-w-[220px] text-[10.5px] leading-snug text-text-muted">
                    {entitlement(school, 'businessOffice').reason}
                  </span>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div className="mt-3 flex items-center gap-2 text-[11.5px] text-text-muted">
        <Mail className="h-3.5 w-3.5 flex-shrink-0 text-text-subtle" aria-hidden="true" />
        <span>
          No spreadsheet to build. {missing.length} emails, and the platform tracks who replies.
        </span>
      </div>
    </AmisaCard>
  );
}

function Th({ children }) {
  return (
    <th className="py-1.5 pr-3 text-[10.5px] font-semibold uppercase tracking-[0.06em] text-text-muted">
      {children}
    </th>
  );
}
